### ISSUE TITLE
AdvertisingFail

### ISSUE THREAD

**Issue by ivangoldenhands** [VikasSukhija/Downloads#1]
Hi,
I'm getting error in report:
AdvertisingTest - AdvertisingFail
And when i'm trying to run this part manualy i see next

Testing server: domain\hostname

   Starting test: Advertising

      Fatal Error:DsGetDcName (hostname) call failed, error 1722

      The Locator could not find the server.

      ......................... hostname failed test Advertising

Windows Server 2012R2

How can i fix this?

**Comment by VikasSukhija** [comment]
seems to be related to your dc, found lot of articles on google related to this.
