### ISSUE TITLE
Space in Table

### ISSUE THREAD

**Issue by krazyuser** [VikasSukhija/Downloads#2]
Hi Vikas, Is there a way to add a space between each servers in the table in the service Status?

![sample](https://user-images.githubusercontent.com/67278327/85300505-9ce9de80-b474-11ea-99ed-fff3235f59b6.png)
 script?

**Comment by VikasSukhija** [comment]
There are couple of ways but you can just add the space in the below code before and after <B>   $svcState   </B> will do the trick.

Add-Content $report "<td bgcolor= 'Aquamarine' align=center><B>$svcState</B></td>"

**Comment by krazyuser** [comment]
You mean add a &nbsp or add space in the line codes?

![2](https://user-images.githubusercontent.com/67278327/85315847-cc571600-b489-11ea-853e-f64037b3e113.png)

**Comment by VikasSukhija** [comment]
![Capture](https://user-images.githubusercontent.com/49596304/85316516-7fbc0c80-b482-11ea-9c17-310379a86416.JPG)

**Comment by krazyuser** [comment]
Tried that and no go :(
![3](https://user-images.githubusercontent.com/67278327/85317619-a8490400-b48c-11ea-8e82-0eeba0e4bb52.png)

**Comment by VikasSukhija** [comment]
Ok will check might need to increase table width then..

**Comment by VikasSukhija** [comment]
I just got time to check the code, I ahev not tested it but I think this will work --> update the space in the table
Add-Content $report  "<td width='10%' align='center'><B>Status</B></td>"

**Comment by krazyuser** [comment]
thanks. will try it out. I did have a another question... How hard would it be to add more columns with this info all at once ??:

Server name | Service Name | Status | Service Start Mode | Server Uptime | Last Reboot

Thanks
