### ISSUE TITLE
I do not understand

### ISSUE THREAD

**Issue by ugintl** [VikasSukhija/Downloads#4]
Would you mind explaining a little about this repo? What it is? WHat is its purpose?

**Comment by VikasSukhija** [comment]
It is scripts repository - common system admin scripts right from Ad  to o365 and azure...

**Comment by Prepsel** [comment]
I'm trying to use IntuneBulkDevicesRemoval.exe but no matter what type of CSV file I use, it tells me that the input is invalid and closes

**Comment by VikasSukhija** [comment]
follow the documentation: https://techwizard.cloud/2020/07/09/intune-bulk-device-removal-tool/
