### ISSUE TITLE
Comment states removing devices from Intune

### ISSUE THREAD

**Issue by wodt** [VikasSukhija/Downloads#7]
https://github.com/VikasSukhija/Downloads/blob/1c12b46db9332a25eea743dfe90642526e91dbe6/IntuneDeviceApplicationFind.ps1#L154

I believe this might just be worded poorly, but the follow section of code does not *remove* any devices from intune, but instead queries intune for every device as to what applications are installed, and adds the intune devices to an array which is later put into the csv report.

**Comment by VikasSukhija** [comment]
Yes, might have used the template from my other code when creating it I will get it fixed.

**Comment by VikasSukhija** [comment]
It has been fixed now
